"use client";

import { useEffect, useRef, useState } from "react";
import {
  ArrowRight, Bell, BookOpen, Bot, CarFront, ChevronRight, CircleHelp, Clock3, Compass,
  Gauge, GraduationCap, Home, Lightbulb, Menu, MoreHorizontal, Play, ShieldCheck,
  Signal, Sparkles, Target, TrafficCone, Trophy, X, Zap
} from "lucide-react";

type Screen = "Home" | "Dashboard" | "Learn" | "Road Signs" | "Police Signals" | "Road Situations" | "Theory Test" | "Driving Simulator" | "Progress" | "AI Coach";
const nav: { label: Screen; icon: typeof Home }[] = [
  { label: "Dashboard", icon: Home }, { label: "Learn", icon: BookOpen }, { label: "Road Signs", icon: TrafficCone },
  { label: "Police Signals", icon: Signal }, { label: "Road Situations", icon: Compass }, { label: "Theory Test", icon: CircleHelp },
  { label: "Driving Simulator", icon: CarFront }, { label: "Progress", icon: Trophy }, { label: "AI Coach", icon: Bot }
];
const lessons = [
  ["Traffic Rules", "The foundations of safer, calmer driving.", "12 lessons", 85, "◈"],
  ["Road Signs", "Read the road before the road reads you.", "24 lessons", 92, "△"],
  ["Police Signals", "Understand every clear instruction.", "10 lessons", 76, "✦"],
  ["Road Safety", "Make better decisions in every situation.", "16 lessons", 68, "✚"],
];
const signs = [
  ["No Entry", "Prohibitory", "Vehicles must not enter this road.", "⛔"], ["Give Way", "Warning", "Yield to traffic on the main road.", "▽"],
  ["Speed Limit", "Mandatory", "Maximum permitted speed is 50 km/h.", "50"], ["Parking", "Information", "Parking is available nearby.", "P"]
];
const theoryQuestions = [
  { q: "You approach a zebra crossing and someone is waiting to cross. What do you do?", a: ["Continue at the same speed", "Slow down and give way", "Flash your headlights", "Sound your horn"], good: 1, why: "Always slow down and give way to pedestrians at a crossing." },
  { q: "What does a continuous centre line mean?", a: ["Parking is allowed", "You may overtake freely", "Do not cross or overtake", "Road works ahead"], good: 2, why: "A continuous line marks a restriction; crossing it is unsafe and not permitted." },
  { q: "An emergency vehicle approaches with siren on. You should:", a: ["Speed up", "Move aside safely and give way", "Stop in the middle of road", "Follow behind it"], good: 1, why: "Give emergency services a clear, safe path without abrupt moves." }
];

function Ring({ value, size = 128 }: { value: number; size?: number }) { return <div className="ring" style={{ width: size, height: size, background: `conic-gradient(#c9ff4a ${value * 3.6}deg, #27312e 0deg)` }}><div><strong>{value}%</strong><small>ready</small></div></div> }
function Bar({ label, value, accent = false }: { label: string; value: number; accent?: boolean }) { return <div className="bar-row"><div><span>{label}</span><b>{value}%</b></div><i><em style={{ width: `${value}%` }} className={accent ? "accent" : ""}/></i></div> }

function Sidebar({ screen, setScreen, open, close }: { screen: Screen; setScreen: (s: Screen) => void; open: boolean; close: () => void }) { return <aside className={`sidebar ${open ? "show" : ""}`}><div className="brand"><span><CarFront size={24}/></span><div>Licence<br/><b>Wallah</b></div><button className="side-close" onClick={close}><X/></button></div><p className="nav-label">MENU</p><nav>{nav.map(({label, icon: Icon}) => <button key={label} className={screen === label || (screen === "Home" && label === "Dashboard") ? "active" : ""} onClick={() => { setScreen(label); close(); }}><Icon size={18}/>{label}</button>)}</nav><div className="side-bottom"><div className="coach-mini"><span><Sparkles size={16}/></span><div><b>AI Coach</b><small>Ready to help</small></div><i/></div><div className="profile"><div className="avatar">A</div><div><b>Arjun Sharma</b><small>Learner driver</small></div><MoreHorizontal size={18}/></div></div></aside> }
function Header({ menu, setScreen }: { menu: () => void; setScreen: (s: Screen) => void }) { return <header><button className="mobile-menu" onClick={menu}><Menu/></button><div className="crumb"><span>LICENCE WALLAH</span><ChevronRight size={15}/><b>DRIVER SPACE</b></div><div className="header-actions"><button className="notification"><Bell size={19}/><i/></button><button className="help"><CircleHelp size={19}/><span>Help centre</span></button><button className="start-test" onClick={() => setScreen("Theory Test")}><Zap size={16}/> Start a test</button></div></header> }

function Landing({ setScreen }: {setScreen:(s:Screen)=>void}) { return <main className="landing"><div className="hero-copy"><div className="eyebrow"><Sparkles size={15}/> THE SMARTER WAY TO LEARN</div><h1>Learn the road.<br/><i>Master the test.</i></h1><p>Build real confidence with an interactive driving-learning experience made for every road ahead.</p><div className="hero-actions"><button className="lime" onClick={()=>setScreen("Dashboard")}>Start learning <ArrowRight size={18}/></button><button className="ghost" onClick={()=>setScreen("Driving Simulator")}><Play size={16} fill="currentColor"/> Try simulator</button></div><div className="trust"><div className="faces"><b>R</b><b>A</b><b>K</b><b>S</b></div><span>Trusted by <strong>14,000+</strong><br/>learner drivers</span></div></div><div className="hero-visual"><div className="visual-top"><span><i/> SYSTEM ONLINE</span><span>TEST MODE <b>•</b></span></div><div className="road"><div className="lane l1"/><div className="lane l2"/><div className="car"><div className="windshield"/><i/><i/></div><div className="cone c1">▲</div><div className="cone c2">▲</div></div><div className="speed-card"><span>CURRENT SPEED</span><b>32 <small>km/h</small></b><i><em/></i><small>Safe driving range</small></div><div className="safe-card"><ShieldCheck/><div><span>SAFETY SCORE</span><b>Excellent · 94%</b></div></div><div className="route-card"><Target/><div><span>CURRENT TASK</span><b>Approach junction</b></div><ChevronRight size={17}/></div></div></main> }

function Dashboard({setScreen}:{setScreen:(s:Screen)=>void}) { return <main className="page dashboard"><section className="intro"><div><p className="eyebrow">FRIDAY, 26 SEPTEMBER</p><h1>Good morning, Arjun <span>👋</span></h1><p>Here&apos;s how your driving journey is looking today.</p></div><div className="streak"><span>🔥</span><div><b>7 day streak</b><small>Keep your momentum going!</small></div></div></section><section className="readiness card"><div className="section-head"><div><p className="eyebrow">YOUR JOURNEY</p><h2>Overall readiness</h2></div><button onClick={()=>setScreen("Progress")}>View detailed progress <ArrowRight size={16}/></button></div><div className="readiness-body"><Ring value={78}/><div className="bars"><Bar label="Traffic Rules" value={85}/><Bar label="Road Signs" value={92}/><Bar label="Police Signals" value={76}/><Bar label="Theory Test" value={81}/><Bar label="Driving Skills" value={68}/></div><div className="ready-note"><ShieldCheck/><b>You&apos;re test-ready soon!</b><p>Just a little more work on driving skills.</p></div></div></section><section className="grid-two"><div className="continue card"><div className="section-head"><div><p className="eyebrow">PICK UP WHERE YOU LEFT OFF</p><h2>Continue learning</h2></div><button className="dots"><MoreHorizontal/></button></div><div className="continue-course"><div className="course-art"><Signal/><span>06</span></div><div><span className="tag">POLICE SIGNALS</span><h3>Understanding hand signals</h3><p>6 of 10 lessons completed</p><i><em style={{width:"60%"}}/></i></div><button onClick={()=>setScreen("Police Signals")}><ArrowRight/></button></div></div><div className="recommended card"><p className="eyebrow">RECOMMENDED FOR YOU</p><div><div className="target-icon"><Target/></div><div><span className="tag orange">PRACTICE DRILL</span><h3>Perfect your U-turn</h3><p>You made 3 U-turn mistakes in your last simulation.</p><button onClick={()=>setScreen("Driving Simulator")}>Practice now <ArrowRight size={15}/></button></div></div></div></section><section className="activity card"><div className="section-head"><div><p className="eyebrow">KEEP IT UP</p><h2>Recent activity</h2></div><button>View all</button></div>{[["Theory test completed", "Scored 17 / 20", "Today, 10:24 AM", "85%"],["Road signs mastered", "Warning signs module", "Yesterday", "100%"],["Simulator practice", "U-turn & parallel parking", "Yesterday", "78%"]].map((x,i)=><div className="activity-row" key={x[0]}><span className={`activity-icon i${i}`}>{i===0?<CircleHelp/>:i===1?<TrafficCone/>:<CarFront/>}</span><div><b>{x[0]}</b><small>{x[1]}</small></div><time>{x[2]}</time><strong>{x[3]}</strong><ChevronRight size={18}/></div>)}</section></main> }

function Learn({setScreen}:{setScreen:(s:Screen)=>void}) { return <main className="page"><section className="intro compact"><p className="eyebrow">BUILD YOUR FOUNDATION</p><h1>Choose your next lesson.</h1><p>Small, focused sessions that make every journey feel more natural.</p></section><div className="learning-grid">{lessons.map(([title,desc,count,prog,symbol],i)=><article className="learning-card" key={title}><div className={`learn-art a${i}`}><span>{symbol}</span></div><div className="learning-info"><div><span className="tag">{count}</span><h2>{title}</h2><p>{desc}</p></div><Bar label="Progress" value={Number(prog)}/><button onClick={()=>setScreen(title === "Road Signs" ? "Road Signs" : title === "Police Signals" ? "Police Signals" : "Road Situations")}>Continue <ArrowRight size={16}/></button></div></article>)}</div></main> }

function Signs(){ const [quiz,setQuiz]=useState(false),[answer,setAnswer]=useState<number|null>(null); return <main className="page"><section className="intro compact"><p className="eyebrow">ROAD SIGNS</p><h1>Read the road at a glance.</h1><p>Know what every sign is asking you to do, before you need to act.</p></section>{!quiz?<><div className="filter-row"><button className="selected">All signs</button><button>Warning</button><button>Mandatory</button><button>Prohibitory</button><button>Information</button><button className="quiz-button" onClick={()=>setQuiz(true)}><CircleHelp size={16}/> Quiz mode</button></div><div className="sign-grid">{signs.map(([name,type,meaning,icon])=><article className="sign-card" key={name}><div className={`sign-illustration ${type.toLowerCase()}`}>{icon}</div><span className="tag">{type}</span><h2>{name}</h2><p>{meaning}</p><small><Lightbulb size={14}/> You&apos;ll see this on test routes</small></article>)}</div></>:<section className="quiz-panel card"><button className="back" onClick={()=>setQuiz(false)}>← Back to signs</button><p className="eyebrow">QUIZ MODE · QUESTION 1 OF 5</p><div className="quiz-body"><div className="quiz-sign">⛔</div><div><h2>What does this sign mean?</h2><div className="answers">{["No Entry","Parking Allowed","Speed Limit","Give Way"].map((a,i)=><button className={answer!==null?(i===0?"correct":i===answer?"wrong":""):""} onClick={()=>setAnswer(i)} key={a}><b>{"ABCD"[i]}</b>{a}</button>)}</div>{answer!==null&&<div className="explain"><ShieldCheck/> <span><b>{answer===0?"Exactly right.":"Not quite."}</b> This sign means no vehicles may enter from this direction.</span><button onClick={()=>setAnswer(null)}>Next <ArrowRight size={16}/></button></div>}</div></div></section>}</main> }

function Police(){const [active,setActive]=useState(0);const data=[["Stop","All traffic facing the officer must stop at the stop line."],["Proceed","Traffic behind the officer may proceed with care."],["Slow down","Reduce your speed and be ready to stop."],["Turn left","Vehicles may turn left when safe."]];return <main className="page"><section className="intro compact"><p className="eyebrow">POLICE SIGNALS</p><h1>Understand every clear instruction.</h1></section><section className="signal-stage card"><div className="officer"><div className="head"/><div className="cap"/><div className="body"><i/><i/></div><div className="arm a-left"/><div className="arm a-right"/></div><div className="signal-copy"><span className="tag">SIGNAL {active+1} OF 4</span><h2>{data[active][0]}</h2><p>{data[active][1]}</p><div className="signal-facts"><div><span>WHO SHOULD ACT</span><b>Approaching drivers</b></div><div><span>REMEMBER</span><b>Eyes up, stay calm</b></div></div></div></section><div className="signal-tabs">{data.map(([x],i)=><button onClick={()=>setActive(i)} className={active===i?"selected":""} key={x}>{x}</button>)}</div></main>}

function Situations(){const [choice,setChoice]=useState<number|null>(null);return <main className="page"><section className="intro compact"><p className="eyebrow">ROAD SITUATIONS</p><h1>Make the right call in the moment.</h1></section><section className="situation card"><div className="intersection"><div className="crosswalk"/><div className="pedestrian">●<br/>╱╲</div><div className="mini-car">▰</div></div><div className="situation-copy"><span className="tag orange">PEDESTRIAN CROSSING</span><h2>A pedestrian is crossing the road. What should you do?</h2><div className="answers">{["Speed up", "Slow down and give way", "Sound the horn and continue", "Overtake the pedestrian"].map((x,i)=><button className={choice!==null?(i===1?"correct":i===choice?"wrong":""):""} onClick={()=>setChoice(i)} key={x}><b>{"ABCD"[i]}</b>{x}</button>)}</div>{choice!==null&&<p className="feedback"><ShieldCheck/> Pedestrians always have priority at a crossing. Reduce speed smoothly and give them room.</p>}</div></section></main>}

function Theory(){const [q,setQ]=useState(0),[selected,setSelected]=useState<number|null>(null),[done,setDone]=useState(false);if(done)return <main className="page result-page"><div className="result-orb"><Trophy/></div><p className="eyebrow">THEORY TEST COMPLETE</p><h1>Strong work, Arjun.</h1><p>You&apos;re building the judgement that makes a safe driver.</p><div className="score"><b>17 <small>/ 20</small></b><span>85% score</span></div><div className="result-grid"><div><ShieldCheck/><b>17 Correct</b><small>Great decisions</small></div><div><Target/><b>3 To revisit</b><small>Practice again soon</small></div><div><Clock3/><b>12:42</b><small>Time taken</small></div></div><button className="lime" onClick={()=>{setDone(false);setQ(0);setSelected(null)}}>Retake test <ArrowRight size={16}/></button></main>;const item=theoryQuestions[q];return <main className="page theory"><div className="test-top"><div><span className="eyebrow">THEORY TEST</span><h2>Question {q+1} <small>/ {theoryQuestions.length}</small></h2></div><div className="timer"><Clock3/> 14:38</div><button>☆ Mark for review</button></div><i className="test-progress"><em style={{width:`${((q+1)/theoryQuestions.length)*100}%`}}/></i><section className="question card"><span className="question-num">{String(q+1).padStart(2,"0")}</span><h1>{item.q}</h1><div className="answers">{item.a.map((a,i)=><button className={selected===i?"picked":""} onClick={()=>setSelected(i)} key={a}><b>{"ABCD"[i]}</b>{a}</button>)}</div><div className="test-actions"><button disabled={q===0} onClick={()=>{setQ(q-1);setSelected(null)}}>← Previous</button><button className="lime" onClick={()=>q===theoryQuestions.length-1?setDone(true):(setQ(q+1),setSelected(null))}>Next question <ArrowRight size={16}/></button></div></section></main>}

function Simulator(){const canvas=useRef<HTMLCanvasElement>(null);const [pos,setPos]=useState({x:180,y:270}),[speed,setSpeed]=useState(8),[mistakes,setMistakes]=useState(1),[running,setRunning]=useState(false);useEffect(()=>{const c=canvas.current;if(!c)return;const x=c.getContext("2d");if(!x)return;x.clearRect(0,0,c.width,c.height);x.fillStyle="#1a2421";x.fillRect(0,0,c.width,c.height);x.strokeStyle="#c9ff4a";x.lineWidth=3;x.strokeRect(26,25,c.width-52,c.height-50);x.strokeStyle="#66706d";x.setLineDash([12,10]);x.beginPath();x.moveTo(45,180);x.lineTo(450,180);x.moveTo(250,45);x.lineTo(250,310);x.stroke();x.setLineDash([]);x.fillStyle="#ff9d5c";[[88,100],[405,95],[380,250],[100,270]].forEach(([a,b])=>{x.beginPath();x.arc(a,b,9,0,Math.PI*2);x.fill()});x.fillStyle="#c9ff4a";x.fillRect(310,230,100,68);x.fillStyle="#f5f6ed";x.fillRect(pos.x,pos.y,30,52);x.fillStyle="#151c1a";x.fillRect(pos.x+5,pos.y+8,20,20)},[pos]);useEffect(()=>{const fn=(e:KeyboardEvent)=>{const key=e.key.toLowerCase();if(!["arrowup","arrowdown","arrowleft","arrowright","w","a","s","d"].includes(key))return;e.preventDefault();setRunning(true);setPos(p=>{let n={...p};if(key==="arrowup"||key==="w")n.y-=10;if(key==="arrowdown"||key==="s")n.y+=10;if(key==="arrowleft"||key==="a")n.x-=10;if(key==="arrowright"||key==="d")n.x=Math.min(430,n.x+10);if(n.x<26||n.y<25||n.y>300){setMistakes(m=>m+1);return p}return n});setSpeed(s=>Math.min(18,s+1))};window.addEventListener("keydown",fn);return()=>window.removeEventListener("keydown",fn)},[]);return <main className="page sim"><div className="sim-head"><div><p className="eyebrow">DRIVING TEST SIMULATOR</p><h1>U-turn practice track</h1></div><span className={running?"live":""}>{running?"● LIVE DRIVE":"○ READY"}</span></div><section className="sim-layout"><div className="canvas-wrap"><canvas ref={canvas} width="500" height="350"/><div className="task-label"><Target/> Current task <b>U-turn</b></div></div><aside className="sim-hud"><div><span><Gauge/> SPEED</span><b>{speed} <small>km/h</small></b></div><div><span><Target/> TASK</span><b>U-turn</b></div><div><span><TrafficCone/> MISTAKES</span><b>{mistakes}</b></div><div><span><Clock3/> TIME</span><b>00:42</b></div></aside></section><div className="drive-controls"><button onClick={()=>setPos(p=>({...p,y:p.y-12}))}>↑</button><button onClick={()=>setPos(p=>({...p,x:p.x-12}))}>←</button><button className="brake" onClick={()=>setSpeed(0)}>BRAKE</button><button onClick={()=>setPos(p=>({...p,x:p.x+12}))}>→</button><button onClick={()=>setPos(p=>({...p,y:p.y+12}))}>↓</button></div><p className="sim-tip"><Lightbulb size={16}/> Use arrow keys or WASD to drive. Keep inside the lime boundary and avoid cones.</p></main>}

function Progress(){return <main className="page"><section className="intro compact"><p className="eyebrow">YOUR PROGRESS</p><h1>You&apos;re 78% road ready.</h1><p>A clear view of your strengths, and your next best moves.</p></section><section className="progress-hero card"><Ring value={78} size={155}/><div className="bars"><Bar label="Traffic Rules" value={85}/><Bar label="Road Signs" value={92}/><Bar label="Police Signals" value={76}/><Bar label="Theory" value={81}/><Bar label="Simulator" value={68}/></div><div className="progress-summary"><span className="tag">THIS WEEK</span><b>+12% <small>improvement</small></b><p>You&apos;re making faster, safer decisions.</p></div></section><section className="grid-two"><div className="card strengths"><p className="eyebrow">YOUR STRENGTHS</p><h2>What&apos;s clicking</h2><p>✓ Reading road signs with confidence</p><p>✓ Strong traffic-rule knowledge</p></div><div className="card needs"><p className="eyebrow">FOCUS NEXT</p><h2>Needs practice</h2><p>⚠ Police-signal timing</p><p>⚠ U-turn control & parking</p></div></section></main>}
function Coach(){const [msgs,setMsgs]=useState([{role:"coach",text:"Hi Arjun — I’ve looked at your latest practice. What would you like to sharpen today?"}]),[input,setInput]=useState(""),[busy,setBusy]=useState(false);const send=async(text=input)=>{if(!text.trim()||busy)return;setMsgs(m=>[...m,{role:"user",text}]);setInput("");setBusy(true);try{const response=await fetch("/api/coach",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text})});const data=await response.json();setMsgs(m=>[...m,{role:"coach",text:data.reply??"I couldn’t respond just now. Please try again."}])}catch{setMsgs(m=>[...m,{role:"coach",text:"I couldn’t connect just now. Please try again."}])}finally{setBusy(false)}};return <main className="page coach"><section className="coach-title"><div className="bot-icon"><Bot/></div><div><p className="eyebrow">YOUR PERSONAL COACH</p><h1>Licence Wallah Coach</h1><p>Ask me about your driving practice.</p></div><span>● Online</span></section><section className="chat card"><div className="messages">{msgs.map((m,i)=><div className={`message ${m.role}`} key={i}>{m.role==="coach"&&<span className="bot-icon"><Bot size={16}/></span>}<p>{m.text}</p></div>)}{busy&&<div className="message coach"><span className="bot-icon"><Bot size={16}/></span><p>Thinking…</p></div>}</div><div className="suggestions">{["Explain my mistakes","How can I improve my U-turn?","Give me a sign quiz"].map(x=><button onClick={()=>send(x)} key={x}>{x}</button>)}</div><form onSubmit={e=>{e.preventDefault();send()}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about your driving practice…"/><button className="lime" disabled={busy}><ArrowRight size={17}/></button></form></section></main>}

export default function App(){const [screen,setScreen]=useState<Screen>("Home"),[menu,setMenu]=useState(false);const content=screen==="Home"?<Landing setScreen={setScreen}/>:screen==="Dashboard"?<Dashboard setScreen={setScreen}/>:screen==="Learn"?<Learn setScreen={setScreen}/>:screen==="Road Signs"?<Signs/>:screen==="Police Signals"?<Police/>:screen==="Road Situations"?<Situations/>:screen==="Theory Test"?<Theory/>:screen==="Driving Simulator"?<Simulator/>:screen==="Progress"?<Progress/>:<Coach/>;return <div className="shell"><Sidebar screen={screen} setScreen={setScreen} open={menu} close={()=>setMenu(false)}/><div className="app"><Header menu={()=>setMenu(true)} setScreen={setScreen}/>{content}</div></div>}
